### ISSUE TITLE
Independable defense towers for Ant and Spider colonies

### ISSUE THREAD

**Issue by Dzierzan** [Dzierzan/OpenSA#10]
Turrets for Ant and Spider colonies need to work independable, that means they need to have own target logic. Currently, both turrets target the same actor.

**Comment by PaweX** [comment]
Cruiser in Red Alert had also two independent turrets, doesn't it work like that in OpenRA?

**Comment by Dzierzan** [comment]
Nope. At first I thought that too, but both turrets target the same target currently. It is not like one shoots a troop and the other shoots a tank.

**Comment by PaweX** [comment]
But it was in the original RA, and that was cool (well, at least this is what I remember). I was trying to recreate it in my mod in RA2 but I couldn't.

**Comment by Dzierzan** [comment]
Original is original, if it was like that, it was certainly cool. But ORA engine doesn't have such functionality cause no matter how many turrets an actor has, they all will target one actor.

**Comment by Mailaender** [comment]
See https://github.com/OpenRA/OpenRA/issues/17185.

**Comment by Dzierzan** [comment]
I am closing this, thing feature is super minor and very unlikely to be implemented. Maybe when DORF game is released and the feature is backported to the main engine, which is also very unlikely to happen.
