### ISSUE TITLE
UI artifacts caused by incorrect chrome regions

### ISSUE THREAD

**Issue by pchote** [Dzierzan/OpenSA#118]
The dark lines are caused by having the region background and border edges next to a hard color transition in the art. Moving inner edge of the border in by 1px is usually enough to fix this.

<img width="606" alt="Screenshot 2020-10-04 at 12 27 26" src="https://user-images.githubusercontent.com/167819/95014274-b7b81b80-063d-11eb-9a4d-e330580d36e4.png">
<img width="466" alt="Screenshot 2020-10-04 at 12 27 43" src="https://user-images.githubusercontent.com/167819/95014275-bb4ba280-063d-11eb-8e66-4daca7bd81ed.png">
<img width="532" alt="Screenshot 2020-10-04 at 12 27 53" src="https://user-images.githubusercontent.com/167819/95014278-bbe43900-063d-11eb-9cca-1df8f04773dd.png">

**Comment by Dzierzan** [comment]
How can I trigger this issue myself?

**Comment by pchote** [comment]
Run OpenSA on a HiDPI screen with a UI scale above 100%.

**Comment by GraionDilach** [comment]
![image](https://user-images.githubusercontent.com/1136302/95016608-551e4a00-0654-11eb-8ba9-cb543fbd916e.png)
