### ISSUE TITLE
Game assets

### ISSUE THREAD

**Issue by neuromancer** [Dzierzan/OpenSA#12]
I wonder if the game assets should be downloaded from the developer website (I guess is [this one](http://www.mking.com/swarmassault_game.html)), instead of having them inside the repository. Another option is to include them in a separated file as a Github release (so the mod will download it automatically).

**Comment by Dzierzan** [comment]
I do acknowledge having game assets in this repository isn't really legal, hence why I am not spreading the word about this project too much. The idea I had was to autodownload game assets from the shareware version of the game (this is what KKND OpenRA project does), however there's a hole in this idea, the shareware doesn't include all needed assets. 

Another thing is that this game is pretty much unknown and I don't expect people to suddenly start buying SA game. Another idea would be just creating own shareware version with needed game assets, putting is somewhere online and downloading game files from it.

**Comment by PaweX** [comment]
> Another thing is that this game is pretty much unknown
I was surprised (in a positive way) when I saw this project on Mod DB, because in fact this game is not well known. I knew it because I had demo on some CD's ages ago, bought in Poland. I really liked SA so I am glad you make this project. Multiplayer was really missing in original SA.
(OpenRA seems to become an engine for remakes of most of old RTSs).

**Comment by Dzierzan** [comment]
Yeah. But currently the project is on hatious. I wish I had someone to help me.

**Comment by PaweX** [comment]
I was actually thinking if it wouldn't be easier to make the game from scratch.

**Comment by Dzierzan** [comment]
That could have been said about other core mods of ORA. Besides, I have no such skills.

**Comment by Dzierzan** [comment]
All sounds and sprites for all entities which are not present in shareware version. At point that'd rather remove game assets from this repo. And I am afraid that recreating missing stuff is out of scope.

**Comment by Nawias** [comment]
Unless you want to stick to the original, have you thought about changing the look of the game completely? Like SuperTuxKart or Hedgewars did with cloning Super Mario Kart and Worms? Then you could look for an artist to do it.

**Comment by Dzierzan** [comment]
No, I wanna keep it as it is now. Different assets mean a different game. This project is supposed to recreate SA game and improve it, just like other mods (RA, C&C, TS, RA2, KKND, DR and so on).

**Comment by Dzierzan** [comment]
Original game asset containers have been removed from the project. They are now autodownloaded.
