### ISSUE TITLE
Battlefield news dropdown displays an error

### ISSUE THREAD

**Issue by pchote** [Dzierzan/OpenSA#121]
<img width="692" alt="Screenshot 2020-10-04 at 12 43 35" src="https://user-images.githubusercontent.com/167819/95014494-411c1d80-063f-11eb-96e5-c8e4fa52a804.png">

**Comment by Dzierzan** [comment]
How do I activate this battlefield news dropdown? I don't see it anywhere.

**Comment by Dzierzan** [comment]
Nevermind, I found it, although in my case, upon clicking it, the dropdown doesn't trigger.
