### ISSUE TITLE
Produce from single captured colony

### ISSUE THREAD

**Issue by kyrreso** [Dzierzan/OpenSA#122]
Sometimes when you capture, you cannot build anything in it. When you start with multiple it worked.

**Comment by Dzierzan** [comment]
Does it happen in skirmish or mission? Maybe both?

**Comment by kyrreso** [comment]
Did only try in mission. Sometimes it works, and sometimes it works after a while.  I capture, press on it, only seeing production tab from last colony... But can set rallypoint...

**Comment by Dzierzan** [comment]
Colony trait most likely needs a refactor in order to fix it.

**Comment by kyrreso** [comment]
![sa-2020-10-04T132545943Z](https://user-images.githubusercontent.com/526956/95143490-7ecf9200-0776-11eb-8581-7283d766dbdd.png)
Btw: it seems to work if I already got one of the same "faction", but if its new type, I cannot build until I capture one more (not sure what type), or I lose another one.

**Comment by Dzierzan** [comment]
Also, an important observation is that on mission 036 (master branch), you start with no colony and you have capture one with your starting troops. Once captured, you cannot produce anything from that colony.

**Comment by kyrreso** [comment]
![sa-2020-10-20T141418548Z](https://user-images.githubusercontent.com/526956/96647864-bae62380-132e-11eb-863a-dd974408a825.png)
Still there in the new 1018.. Helps if you capture one more. That kinda makes it hard to win some of the missions....

**Comment by Dzierzan** [comment]
It hasn't been fixed yet. There's a PR which makes Colony trait less hacky and from my tests of it, this bug should be gone. But the pull request still requies a lot of polishment before it can be merged. https://github.com/Dzierzan/OpenSA/pull/146

As soon as this bug is fixed, I'll surely make a new release.

**Comment by Dzierzan** [comment]
Alright. This is fixed now!
