### ISSUE TITLE
Moth creep flyer's bombs sometimes don't explode.

### ISSUE THREAD

**Issue by MikillRosen** [Dzierzan/OpenSA#127]

**Comment by Dzierzan** [comment]
Moth flyers drops two "bombs", one is explosive seed and the other one is "normal" seed. This one lands on the ground and has a random chance of spawning Seed Ball plant.

`moth:
	Inherits: ^Bomber
	Tooltip:
		Name: Spawn Moth
	Health:
		HP: 16000
	Aircraft:
		Speed: 220
	Voiced:
		VoiceSet: NeutralVoice
	SpawnsShrapnel@puff:
		Weapon: moth
		Delay: 50
		AimChance: 0
		Amount: 5
	SpawnsShrapnel@normal_seed:
		Weapon: puff_normal_seed
		Delay: 50
		AimChance: 0
		Amount: 1
	AmbientSound:
		SoundFiles: sounds|MOTHFLUTTER.SDF`

**Comment by Dzierzan** [comment]
Ohh and Seed Balls have the same logic, they also drop explosive and normal seeds.
