### ISSUE TITLE
Can't command wasps to fly over water in spite of wasps being able to fly over water.

### ISSUE THREAD

**Issue by MikillRosen** [Dzierzan/OpenSA#129]

**Comment by Dzierzan** [comment]
Yeah, in the original game, they can do it. Right now Wasps use modified jet infantry logic (so they can cross water and still kinda behave like land units). They can't go into the water tiles directly cause it causes another problem, they can "land" on water if you've got a handful of them. 

As a matter of fact, in the original game if they "stop" on water tile, they try to land on the closest terrain tile. I guess it won't hurt if they could hover over water, they should just use flying animation as hovering.

**Comment by Dzierzan** [comment]
Improved and fixed!

![wasps](https://user-images.githubusercontent.com/17529329/111367468-0fe75500-8695-11eb-96ee-37de07ac39e4.gif)
