### ISSUE TITLE
Divide by zero crash.

### ISSUE THREAD

**Issue by MikillRosen** [Dzierzan/OpenSA#131]
[exception-2020-10-05T105050Z.log](https://github.com/Dzierzan/OpenSA/files/5326899/exception-2020-10-05T105050Z.log)

**Comment by Dzierzan** [comment]
Any idea when this exactly happened?

**Comment by MikillRosen** [comment]
I was playing mission 19. Here's the replay: [sa-2020-10-05T104646Z.zip](https://github.com/Dzierzan/OpenSA/files/5326917/sa-2020-10-05T104646Z.zip)

**Comment by Mailaender** [comment]
Running the replay on tag 20201004 desyncs the game for me.

> Exception of type `System.InvalidOperationException`: Out of sync in frame 894.

Did you modify the game files in any way?

**Comment by MikillRosen** [comment]
> Did you modify the game files in any way?

No
