### ISSUE TITLE
Restarting a mission or a skirmish freezes the game

### ISSUE THREAD

**Issue by Dzierzan** [Dzierzan/OpenSA#136]
It doesn't happen every time, but there's a high chance it might happen.

**Comment by Dzierzan** [comment]
This is still happening.

**Comment by Dzierzan** [comment]
And reopening again, this is still happening.

**Comment by GraionDilach** [comment]
https://github.com/OpenRA/OpenRA/issues/18691 probably.

**Comment by Mailaender** [comment]
Should have been fixed by https://github.com/Dzierzan/OpenSA/pull/170 then.

**Comment by Dzierzan** [comment]
Seems to be working fine with the current branch. I'll close it again.
