### ISSUE TITLE
AI chases creep flyers infinitely

### ISSUE THREAD

**Issue by Dzierzan** [Dzierzan/OpenSA#142]
Due to creep flyers flying over the battlefield, AI units can stupidly chase them which usually leads to their death.

Creep flyers: dragonfly, fly, moth, flying_machine

@GraionDilach

**Comment by GraionDilach** [comment]
This isn't forgotten, life's just a bit busy lately.

**Comment by Dzierzan** [comment]
Since I changed AI's initial stance to `Defense`, they're not so likely to chase creep flyers. So I'll close this issue.
