### ISSUE TITLE
macOS dmg background needs a lighter coloured section behind the filename text

### ISSUE THREAD

**Issue by pchote** [Dzierzan/OpenSA#148]
![Screenshot 2020-10-18 at 16 49 08](https://user-images.githubusercontent.com/167819/96373245-18c61000-1163-11eb-9934-64a22676f35f.png)

**Comment by pchote** [comment]
The background image also changes when dragging the window between low and hi dpi monitors.

Notice how everything gets smaller, and the central arrow changes:
<img width="603" alt="Screenshot 2020-10-18 at 19 30 55" src="https://user-images.githubusercontent.com/167819/96376714-803a8a80-1178-11eb-9e4b-47c9dcd8d89d.png">

The 2x assets are supposed to match the 1x, but be crisper. In this case, you can do a nearest-neighbour pixel doubling on the world background, and use higher resolution assets (if you have them) for the logo text.

**Comment by Dzierzan** [comment]
Would something like that be OK?

![macos-background](https://user-images.githubusercontent.com/17529329/97765518-b120a500-1b12-11eb-9372-9008f25bfdf7.png)

**Comment by pchote** [comment]
What if you put a gold / sandy coloured hexagon behind the whole icon instead?

**Comment by Dzierzan** [comment]
I am not sure to be honest. I'll make a mockup.

**Comment by Dzierzan** [comment]
Although wouldn't such sandy hex collide with OpenSA logo which is also sandy-ish?

**Comment by pchote** [comment]
Not sure, that is what I was asking you? 😄

**Comment by Dzierzan** [comment]
![macos-background](https://user-images.githubusercontent.com/17529329/97786827-83893980-1bae-11eb-8bbd-467c36e049e9.png)

**Comment by Dzierzan** [comment]
I think it's good enough. The words should be better visable. I am going to commit that.
