### ISSUE TITLE
Losing all of your units with no colonies doesn't fail a mission.

### ISSUE THREAD

**Issue by MikillRosen** [Dzierzan/OpenSA#152]

**Comment by Dzierzan** [comment]
Wait, every mission has at least one colony... apart from the final 100th one. So you mean that if I lose all units, while not owning a colony doesn't fail a mission? I had a situation where I lost everything and the game did register that as a failure.

**Comment by MikillRosen** [comment]
> So you mean that if I lose all units, while not owning a colony doesn't fail a mission?
Yes.

**Comment by Mailaender** [comment]
Can not reproduce the problem:

![image](https://user-images.githubusercontent.com/756669/105575034-c64f4d80-5d68-11eb-8394-560ddd85a51b.png)

**Comment by Dzierzan** [comment]
@Mailaender Try map 036 and lose all your units. The game won't end.
