### ISSUE TITLE
Mission Description For Tutorial Levels (I'm bad at the game and would like a guide of some sort)

### ISSUE THREAD

**Issue by StevenWilson9** [Dzierzan/OpenSA#153]
On mission 006), where the player starts with a bettle colony and has to fight a spider colony, I can not win. I've tried: 
- None of the 3 unit types I can produce are effective at combating the spiders, and the spiders also outrange the bettles. 
- I also could not kill the neutral ant colony in time to aid in the defense against the spiders.
- I'm probably not seeing some game mechanic I need to know to win this.

As mission 10 is called "Training complete" I think I'm still in the learning mechanics part of the game. However I'm unable to learn the mechanic being taught in mission 6.

**Comment by Dzierzan** [comment]
Hi!

Well, this mission inherits difficulty from the original game. It was even harder in the previous version 20201004, all sent units were in AttackMove mode. Anyway, right now two Missiles and two Spiders will attack your base as soon as you start the mission. They will ignore all your other actors, use Soldiers to kill them and produce 2-3 Lady Bugs to aid them. After that, I'd recommend sending one Cannon to Ants Colony and then keep builing Shrapnel bugs. They have small range, but they are the tankiest units in the game (high amount of HP).

I might lower the difficulty even more, as in the original game, if AI has Spiders Colony and access to Missile Spiders, it will ALWAYS send one spider at a time. Which obviously makes the mission less troublesome.

And those are also original names, so, yeah, first 10 missions are more or less training. I gotta write some kind of tutorial to explain all mechanics. For example, the game doesn't teach you that each faction specializes in own units, that means if you play as Ants (green color), production time of only Ant units is decreased by 25%

**Comment by Dzierzan** [comment]
I have been thinking about this. I am not sure if writing any descriptions to mission is really that needed. I mean this game doesn't have a lot of mechanics here and it is pretty much self-explanatory. Sure, mission 10 has name "Training Complete", but it's not my fault original developers named it like that.

It's basically:
1. Build army.
2. Capture colonies by destroying them and collecting their colony bits.
3. Each faction gets -25% breeding time for their specialized units.
4. To heal colony, stop production.

The rest is just how well you handle missions. 

I think I'll close it for now to clean up issues.
