### ISSUE TITLE
Game crashed when I loaded a save file (again.)

### ISSUE THREAD

**Issue by MikillRosen** [Dzierzan/OpenSA#154]
This time it's after it loaded a save file.
[exception-2020-10-19T083719Z.log](https://github.com/Dzierzan/OpenSA/files/5400337/exception-2020-10-19T083719Z.log)

**Comment by Dzierzan** [comment]
`Out of sync in frame 2828.` this doesn't tell me much plus I just tested it in my master branch (which is only one commit ahead of release version) and the game didn't crash.

**Comment by MikillRosen** [comment]
Here's the save file (for release 20201018)
[040) The Castle.zip](https://github.com/Dzierzan/OpenSA/files/5401805/040.The.Castle.zip)

**Comment by Dzierzan** [comment]
Yeah, this save does crash for me too. Hard to say what's the cause of this. Normally saving and loading works fine. Do you play the mission for long time?

**Comment by MikillRosen** [comment]
no

**Comment by Dzierzan** [comment]
Been testing that. Yeah, there's a problem. Probably due to custom traits added to the mod. This might take some time before it is fully fixed.
