### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Dzierzan** [Dzierzan/OpenSA#161]
[exception-2020-11-02T194241Z.log](https://github.com/Dzierzan/OpenSA/files/5477636/exception-2020-11-02T194241Z.log)

I suspect this is related to new `InvalidBounceTerrain:` as this crash was never happening before.

**Comment by GraionDilach** [comment]
It's definitely that, probably on a map border cell.

**Comment by Dzierzan** [comment]
Fixed
