### ISSUE TITLE
HealColonyBotModule trait doesn't work

### ISSUE THREAD

**Issue by Dzierzan** [Dzierzan/OpenSA#162]
HealColonyBotModule trait appears to be not working. I tried all damage states but AI wasn't eager to heal colonies.

@Mailaender

**Comment by Mailaender** [comment]
I can't reproduce your problems.

**Comment by Dzierzan** [comment]
How much HP is AI supposed to heal? I can't figure this out from the code. I only understand that by default if HP is in its critical state, it should heal, right?

**Comment by Mailaender** [comment]
Until it is not critical anymore.

**Comment by Dzierzan** [comment]
Ok, this logic actually works fine. I have no idea why it didn't work for me, but now it does. Closing.
