### ISSUE TITLE
Random loading screen

### ISSUE THREAD

**Issue by Dzierzan** [Dzierzan/OpenSA#167]
In original Swarm Assault game, when a mission/skirmish map is being loaded, random loading screen can be seen.

**Comment by Dzierzan** [comment]
This might be useful:

https://github.com/patrickwieth/OpenRA/commit/06acec8a30e30eb771f63f62a7da65fa3ac5d0aa

Yaml code:

`LoadScreen: FitImageLoadScreen
    Image: ra|uibits/loadscreen1.png,ca|uibits/loadscreen2.png,ra|uibits/loadscreen3.png,ra|uibits/loadscreen4.png,ra|uibits/loadscreen5.png`

**Comment by Mailaender** [comment]
Do you have artwork that you want to display instead of the logo?

**Comment by Dzierzan** [comment]
They're in Loading00.DDF, Loading01.DDF, Loading02.DDF. The project needs to first download these, they're in the zip which the assets are downloaded from.
