### ISSUE TITLE
Mission accomplished for no reason.

### ISSUE THREAD

**Issue by wandsmire** [Dzierzan/OpenSA#179]
Hi, the latest build is awesome. The new minimap looks great.

I just want to report a bug:
Mission accomplished for no reason. Latest build. Mission 8.
https://www.dropbox.com/sh/4ct3h9youenj7ob/AAAb33ok26ylZplapcvt-eB3a?dl=0

Thank you.

**Comment by Dzierzan** [comment]
Alright, I can confirm that. Thanks for testing!

@Mailaender This might be a regression caused by PR which fixed this #152.
