### ISSUE TITLE
Units keep attacking dead colonies

### ISSUE THREAD

**Issue by wandsmire** [Dzierzan/OpenSA#180]
Hi, me again... found another bug.

Mission 4. Latest build. Mac OS. 
Way to reproduce: build some ladybug, destroy the north-east colony.
https://www.dropbox.com/s/m4kj8kpyslm5x0p/issue.png?dl=0

**Comment by Dzierzan** [comment]
Confirmed. Although it is kinda weird why it's happening on this particular colony. I thought that this would be happening to all colonies.

**Comment by Dzierzan** [comment]
Alright, apparently "Neutral" was one of the enemies, hence it was happening. It was also happening on 003 mission. Anyway, it's fixed now. Thanks for heads up.
