### ISSUE TITLE
An ally inside a campaign...

### ISSUE THREAD

**Issue by wandsmire** [Dzierzan/OpenSA#183]
Thanks for the last fix, it is great.
However, I found another bug.

Latest build, mission 8 (again): the red team would not attack the player. Yet, player can attack them.
<img width="1440" alt="Jepretan Layar 2021-02-05 pukul 16 49 00" src="https://user-images.githubusercontent.com/2555779/107018659-4b0f8200-67d3-11eb-8c26-efc5b8dccc4a.png">
<img width="989" alt="Jepretan Layar 2021-02-05 pukul 16 50 20" src="https://user-images.githubusercontent.com/2555779/107018666-4d71dc00-67d3-11eb-9c7b-af6425b8de9c.png">

Thank you.

**Comment by Dzierzan** [comment]
Alright. I took a look on my Phone. Looks like "Ants faction - the green color" is not set as one of Spiders' enemies for this map. Spiders faction is the enemy of themselves according to map.yaml :). I will fix it when as soon as i am at home.

Thanks for playtesting this project.

**Comment by Dzierzan** [comment]
Fixed
