### ISSUE TITLE
Wasps units land on water after chasing a flyer

### ISSUE THREAD

**Issue by wandsmire** [Dzierzan/OpenSA#185]
Mission 14, latest build, macOS.

Enemy sonic was chasing a flyer and landed on water. Unfortunately, player's wasps cannot attack them as they were not on land.

<img width="1430" alt="Jepretan Layar 2021-02-06 pukul 11 55 37" src="https://user-images.githubusercontent.com/2555779/107109398-b8bebb00-6872-11eb-8ba7-6dfd4c42d934.png">

**Comment by Dzierzan** [comment]
This is more or less related to #129. The whole logic needs a refactor.

**Comment by Dzierzan** [comment]
I decided to not follow original Swarm Assault (they try to land on ground as soon as they stop on water tile) and now Wasps can go into the water and hover above it.

![wasps](https://user-images.githubusercontent.com/17529329/111367180-c139bb00-8694-11eb-863a-da21711380fe.gif)

So problem solved!
