### ISSUE TITLE
Clicked actors on production tab should use clicked state

### ISSUE THREAD

**Issue by Dzierzan** [Dzierzan/OpenSA#191]
I would be great if a clicked actor on production tab was using **icon-clicked** state.

![87661491-fc2fcb80-c760-11ea-8c71-8e27698363cb](https://user-images.githubusercontent.com/17529329/111024509-717e9980-83df-11eb-8338-d53d2ecc885d.gif)

**Comment by IceReaper** [comment]
It lies within the production palette code. It does not support -highlighted or such suffixes. Only the clock to be rendered on top. Thats not a big issue, but requires a PR on OpenRA itself. Other solution: (let) Write your own sidebar. It pretty simplistic anyway.
