### ISSUE TITLE
Lack of Mac support for the latest release.

### ISSUE THREAD

**Issue by FrediWest** [Dzierzan/OpenSA#193]
I know this game was originally made for windows, but any possibility there will be Mac support?

**Comment by Dzierzan** [comment]
But there's already installer for Mac. Although you mean original Swarm Assault? If so, then there's no way to support Mac, but if you mean OpenSA project, then it supports Windows, Linux and Mac.

**Comment by FrediWest** [comment]
> But there's already installer for Mac. Do you mean original Swarm Assault, though? If so, then there's no way to support Mac, but if you mean OpenSA project, then it supports Windows, Linux and Mac.

Thank you, found it. The latest release only had the windows version but I was able to find the Mac version in one of your previous release.

**Comment by Dzierzan** [comment]
Reopening. Actually you made a good point, my latest playtest version has no Mac installer.

**Comment by Dzierzan** [comment]
@FrediWest 
Alright, I fixed issues, Mac dmg should in the latest playtest version 

https://github.com/Dzierzan/OpenSA/releases/tag/playtest-20210319

**Comment by FrediWest** [comment]
> @FrediWest
> Alright, I fixed issues, Mac dmg should in the latest playtest version
> 
> https://github.com/Dzierzan/OpenSA/releases/tag/playtest-20210319

Oh thank you much appreciated.
