### ISSUE TITLE
"Check for Updates" doesn't work

### ISSUE THREAD

**Issue by FrediWest** [Dzierzan/OpenSA#198]

**Comment by Dzierzan** [comment]
Hi! Can you be more specific? I don't remember any such feature in OpenSA. Maybe it's something from OpenRA?

**Comment by FrediWest** [comment]
> Hi! Can you be more specific? I don't remember any such feature in OpenSA. Maybe it's something from OpenRA?

![Screen Shot 2021-03-28 at 3 28 52 PM](https://user-images.githubusercontent.com/79551523/112767109-71cf8500-8fda-11eb-9160-54b0cd50c8f5.png)

There's an option to check for updates in the settings, but it doesn't do anything.

**Comment by Dzierzan** [comment]
Thanks, I see. Yeah, most likely I totally skipped or forgotten that. It's something worth doing for the next version.

**Comment by Dzierzan** [comment]
BTW, you have to manually update the mod for time being. You are using 202103021 right now. The latest version is 20210327,
