### ISSUE TITLE
Arrow key support for navigitaing the asset browsing

### ISSUE THREAD

**Issue by MikillRosen** [Dzierzan/OpenSA#201]
Make the asset browser use the arrow keys since every frame of animation is a separate file.

**Comment by Dzierzan** [comment]
There used to be both ani and ddf in asset brower, where the first one was animated. @Mailaender didn't you remove that?

**Comment by Mailaender** [comment]
Yes, https://github.com/Dzierzan/OpenSA/commit/b1e642f9d2322f6a05af6bf8b23fd7885b41a308
