### ISSUE TITLE
Add the palette for the Swarm Assault menu graphics in the asset browser

### ISSUE THREAD

**Issue by MikillRosen** [Dzierzan/OpenSA#202]

**Comment by Dzierzan** [comment]
Can you be more specific? OpenSA is the Swarm Assault palette.

![image](https://user-images.githubusercontent.com/17529329/112903655-1e4b5d00-90e8-11eb-89ca-3e81aa4f8a1c.png)

**Comment by MikillRosen** [comment]
OpenSA doesn't have a palette for some menu graphics like this credits screen
![Untitled](https://user-images.githubusercontent.com/51423707/112904855-dfb6a200-90e9-11eb-83ad-42adce076f56.png)

**Comment by Dzierzan** [comment]
Ohh that. I don't use those graphics and their implementation or reverse engineering was never done.

**Comment by Dzierzan** [comment]
I closed wrong issue...

**Comment by Dzierzan** [comment]
Sorry, it's a "wontfix" case.
