### ISSUE TITLE
Please add native Apple silicon support.

### ISSUE THREAD

**Issue by CollinsVakayil** [Dzierzan/OpenSA#210]

**Comment by CollinsVakayil** [comment]
Any updates??

**Comment by GraionDilach** [comment]
https://github.com/OpenRA/OpenRA/issues/19805 was resolved so when the project migrates to a ModSDK version based on OpenRA's next version, the issue will be automatically resolved.

**Comment by CollinsVakayil** [comment]
> [OpenRA/OpenRA#19805](https://github.com/OpenRA/OpenRA/issues/19805) was resolved so when the project migrates to a ModSDK version based on OpenRA's next version, the issue will be automatically resolved.

Do you know how long this will take? No joke I've been checking this GitHub page regularly hoping it would be soon.

**Comment by Dzierzan** [comment]
#19889 is the PR I am waiting to be merged as it's one of features OpenSA needs. Besides, what Graion posted appears to be part of Bleed branch. Right now OpenSA engine is based on release branch of OpenRA. If I want to make a new version, I'd have to base it on bleed branch, potentially less stable branch.

We'll see.

**Comment by CollinsVakayil** [comment]
> [OpenRA/OpenRA#19889](https://github.com/OpenRA/OpenRA/pull/19889) is the PR I am waiting to be merged as it's one of features OpenSA needs. Besides, what Graion posted appears to be part of Bleed branch. Right now OpenSA engine is based on release branch of OpenRA. If I want to make a new version, I'd have to base it on bleed branch, potentially less stable branch.
> 
> We'll see.

Thank you for your time, effort and contribution in keeping this game alive.
