### ISSUE TITLE
Modding options?

### ISSUE THREAD

**Issue by CollinsVakayil** [Dzierzan/OpenSA#222]
Will there be an option to re-skin the game or change textures or other modding capabilities? Don't get me wrong this game is timeless, but wouldn't mind seeing better graphics or textures. This way may be we don't have to depend on the original game from 20 years ago for assets but actually have some breathing room in terms of the game itself.

**Comment by Dzierzan** [comment]
Of course it's fully moddable, as this project uses OpenRA engine. That means you can change art, change code, make your own code and so on and so on. You've got full access to the source code :-).

**Comment by CollinsVakayil** [comment]
Oh thank you for clarifying that. Forgive my ignorance on the topic.

**Comment by Dzierzan** [comment]
BTW you are actually interested in making libre assets?
