### ISSUE TITLE
AI issue: Scorpion's colony turret won't switch target

### ISSUE THREAD

**Issue by Blackrobe** [Dzierzan/OpenSA#234]
How to reproduce:
- Have a small group of unit attack an AI player scorpion colony, the spearhead unit acting as a bait, kiting the harpoons shot by the colony building.
- Walk the kiting unit outside the scorpion colony's attack range.
- Observe that the scorpion colony won't switch target.

Video demonstration: https://youtu.be/84ibwx328Io

May or may not affect other faction's colony turret.

**Comment by Dzierzan** [comment]
Hey, thanks for the report. I just tried to reproduce that and I had no luck. Does it happen everytime?

Moveover, I would have noticed that bug myself as I was using that kiting method as well, but the turrets were always properly changing targets. Besides, all turrets in OpenSA use the same `Turret` logic.

**Comment by Blackrobe** [comment]
Pretty consistently reproduced for me @Dzierzan, I'm using 20230730. 

It's just like the demonstration video, when the kiter is placed just one tile outside the turret's range. This is not happening when tested with neutral (grey) colonies.

But I was suspecting that it is a line-of-sight problem, related with turret range. Just a guess though.

**Comment by Blackrobe** [comment]
If the `Turret` logic is inherited from OpenRA, then could it be that we can't do anything but wait for the upstream fix it?

**Comment by Dzierzan** [comment]
Alright, I didn't realize one thing. You were playing a skirmish map. Yeah, this is an issue related to the line of sight. I was never really heavily testing skirmish mode, hence I never noticed it.

Nevertheless, I was able to reproduce that and fix it. LOS will equal to weapon range.

**Comment by Blackrobe** [comment]
Thanks @Dzierzan ! Looking forward to the next release 😃

**Comment by Dzierzan** [comment]
It might take a huge while before that happens as right now I don't have any ideas for new features. Although there's always room to improve something.

If you play OpenSA alone, you might wanna change that in your local copy:
https://github.com/Dzierzan/OpenSA/commit/2929fc80047e7c6aed37c072be3463217371084a

**Comment by Blackrobe** [comment]
sure, I can try building it myself.

By the way, I found similar issue with this one with wasp faction's Sonic.

When a group of them ordered to attack colonies from an angle, some just land outside their attack range and do nothing.

I'll post it in another new issue after I'm done collecting the evidence.

**Comment by Dzierzan** [comment]
@Blackrobe 
If you find anything, let me know. I'd love to release a new emergency release next month to fix no visable tiles in map editor.
