### ISSUE TITLE
Classic mode, please?

### ISSUE THREAD

**Issue by NastyFlytrap** [Dzierzan/OpenSA#239]
As a fellow swarm assault enjoyer, i very much appreciate your work, and i dont doubt that your changes make the game better, but i just would like to play Swarm Assault with this source port as the original game was intended, for nostalgia's sake, and then i'll probably turn on your enhancements for playing after that.

Please create a button or a switch in the menu somewhere that turns on 'vanilla mode' and turns off all of your personal changes, so the port becomes as 1:1 to the original as possible.

Edit: Any chance you could make a port for swarm rampage too?

**Comment by Dzierzan** [comment]
Hi,
it's not a source port, as it was recreated in OpenRA engine. 

Anyway, my interest in OpenSA project has drained out as I consider this project basically completed-ish. Sure, there is still stuff to improve like weapons of some creep flyers are not recreated perfectly or seeing original lose/win animation would be nice. But overall, it's playable for most of the people, whether those are old fans of SA game or newcomers.

Please, consider this project more like a modification of SA game, not a project trying to recreate it faithfully. As a matter of fact, my first intent was to make it as close as possible to the original game, but I realized not everything was that fun, so I kept adding enhancements, while keeping the core of the game.

> Edit: Any chance you could make a port for swarm rampage too?

If **IceReaper** user reverse engineers SR's asset containers, then my answer is "maybe". It's generally on his to-do list. Also keep in mind while I did play SR, I didn't like it that much, although it did have some nice ideas which were backported to OpenSA like new buildings or ideas for creep plants.
