### ISSUE TITLE
Seperate music for each tileset

### ISSUE THREAD

**Issue by Dzierzan** [Dzierzan/OpenSA#3]
Original game has invidual music/ambient for each tileset.

**Comment by Mailaender** [comment]
What are the music filenames exactly?

**Comment by Dzierzan** [comment]
"FROGS.SDF" for Normal tileset
"WIND.SDF" for Desert tileset
"CRICKETS.SDF" for Swamp tileset
"DREAMSCAPE.SDF" for Candy tileset

**Comment by Mailaender** [comment]
Can't get them to play:

```salt
FROGS: FROGS
	Extension: SDF
	Filename: sounds|FROGS
```

Tried multiple things for `music.yaml`. It seems the files don't exist.
