### ISSUE TITLE
Update Readme with precise install instructions

### ISSUE THREAD

**Issue by Nawias** [Dzierzan/OpenSA#78]
I tried to run the project on a clean linux installation today, and I needed to jump some hoops related to engine dependencies to get it working. I think that README.md should contain more precise installation information.

**Comment by Dzierzan** [comment]
Yeah, I have been thinking lately about major overhaul for the Readme. Thanks for the heads up.

**Comment by Dzierzan** [comment]
Apparently OpenRA has detailed instruction for that https://github.com/OpenRA/OpenRA/blob/bleed/INSTALL.md. I put the link to this in README.md.
