### ISSUE TITLE
Swarm Assault assets

### ISSUE THREAD

**Issue by LiamDawe** [Dzierzan/OpenSA#97]
Hi, been following this for a while and just wanted to clear something up.

How are you dealing with the original Swarm Assault assets? Since it's not been made open source, and it seems there's nowhere to legally buy it easily now.

**Comment by Dzierzan** [comment]
Hi! It's very vague. As I commented this in #12, original game assets have been removed from this project and they are now autodownloadable from external source. It's not 100% legal either, but as you mentioned it, the game cannot be purchased from any legal source and the IP holder of Swarm Asasult and Swarm Rampage games doesn't want to support them (I asked Mountain King Studios why SA and SR games cannot be purchased on their website).

So, although it's not an official term, I consider Swarm Assault an abandonware.

**Comment by LiamDawe** [comment]
I see thanks, so mechanically it works like OpenRA in that it will download it. Thanks.

This would be another ideal case for GOG to revive...

**Comment by Dzierzan** [comment]
So alright, since this was the question only, I am closing this issue.

**Comment by Dzierzan** [comment]
Well, to put the final nail to this coffin, I asked those Mountain King Studios guys (or a guy) about why not puting Swarm Assault and perhaps Swarm Rampage on GoG. Apparently, this studio doesn't own those games, thus they can't sell them. I suppose the original creators still own these games, but they are not traceable anywhere on the Internet.

I guess naming SA or SR games abandonware is not that far from the reality now.
